language: node_js

dist: xenial

services: 
  - xvfb

node_js:
  - stable

before_install:
  - chmod +x ./deploy.sh && ./deploy.sh

install:
  - npm install

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - npm run eslint
  - npm test

# Send coverage data to Coveralls
after_script: "cat coverage/report-lcov/lcov.info | node_modules/coveralls/bin/coveralls.js"